name: Deploy To Rana8 by GitHub Actions
on: [push]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - shell: bash
        env:
          KEY_FILE: ${{ secrets.KEY_FILE }}
        name: save key file into local
        run: make saveKeyFile
      - shell: bash
        env:
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
        name: deploy to rana8
        run: make deploy
