name: Deploy To Rana8 by GitHub Actions
on: [push]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: save key file into local
        run: make saveKeyFile
      - run: make setup