name: Deploy To Rana8 by GitHub Actions
on: [push]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - shell: bash
        env:
          KEY_FILE: ${{ secrets.KEY_FILE }}
        name: save key file into local
        run: make saveKeyFile
      - shell: bash
        env:
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          RANA8_DB_HOST: ${{ secrets.RANA8_DB_HOST }}
          RANA8_DB_PORT: ${{ secrets.RANA8_DB_PORT }}
          RANA8_DB_USER: ${{ secrets.RANA8_DB_USER }}
          RANA8_DB_PASSWORD: ${{ secrets.RANA8_DB_PASSWORD }}
          RANA8_DB_NAME: ${{ secrets.RANA8_DB_NAME }}
        name: deploy to rana8
        run: make deploy
